spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/departments/**

server:
  port: 9191
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone:http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

